I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    $ num_of_people = num_of_people_at(0)
  File "game/script.rpy", line 30, in <module>
    $ num_of_people = num_of_people_at(0)
  File "game/py_script.rpy", line 77, in num_of_people_at
    renpy.notify(character_schedules[0][0][1]);
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    $ num_of_people = num_of_people_at(0)
  File "C:\Users\hlynk\OneDrive\Desktop\UNIVERSITY\PhD_Calreton\Classes\F22_COMP_5900_J_game_dev_technologies\renpy-8.0.3-sdk.7z\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\hlynk\OneDrive\Desktop\UNIVERSITY\PhD_Calreton\Classes\F22_COMP_5900_J_game_dev_technologies\renpy-8.0.3-sdk.7z\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 30, in <module>
    $ num_of_people = num_of_people_at(0)
  File "game/py_script.rpy", line 77, in num_of_people_at
    renpy.notify(character_schedules[0][0][1]);
  File "C:\Users\hlynk\OneDrive\Desktop\UNIVERSITY\PhD_Calreton\Classes\F22_COMP_5900_J_game_dev_technologies\renpy-8.0.3-sdk.7z\renpy-8.0.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Test_Scheduling_v02 1.0
Fri Nov  4 18:05:50 2022
